test_that("rope() returns the correct values.", {
  expect_equal(rope(NA_real_), NA_real_)
  expect_equal(rope(NA_integer_), NA_real_)
  expect_equal(rope(numeric(0)), NA_real_)
  expect_equal(rope(seq(-0.1, 0.1, by = 0.01)), 1)
  expect_equal(rope(0), 1)
  expect_equal(rope(1:100), 0)
  expect_equal(rope(c(0, Inf)), 0.5)
  expect_equal(rope(c(rep(Inf, 19), 0)), 0.05)
  expect_equal(rope(c(Inf, Inf)), 0)
  expect_equal(rope(c(-Inf, Inf)), 0)
  expect_equal(rope(seq(0, 1, length.out = 1e3)), 0.1)
  expect_equal(rope(seq(-1, 1, length.out = 2e3)), 0.1)
  expect_equal(rope(seq(-0.1, 0.3, length.out = 2e3)), 0.5)
})
