# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_lik_beta_binom2 <- function(x, size, prob, theta) {
    .Call('_extras_log_lik_beta_binom2', PACKAGE = 'extras', x, size, prob, theta)
}

